### ISSUE TITLE
cragList Issue #5_singleRoutePage

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/capstone-project#4]
## Value Proposition

**As a** user

**I need** have a info page for a single route

**to be able to** see details about a single route

## Description

![Image](https://user-images.githubusercontent.com/115465230/212095935-3e2b0fd9-6785-4fb5-a189-3932a86ea32d.png)

## Acceptance Criteria

- [x] Infopage needs to show all details about the route
- [x] Include Images
- [x] See the location on a map
## Tasks

(for developers team)

- [x] create dynamic InfoPage Component
- [x] create Image container 
- [x] create a table for display all details
- [x] create a map section below the infos
- [x] responsive design
- [x] scrollbar (vertical)
- [x] create Pullrequest
