### ISSUE TITLE
userStorie#6_routesInOneSector

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/capstone-project#5]
## Value Proposition

**As a** user
**I want to** have an overview about all routes in my current sector 
**so that** I don't have to research too many routes at once
​

## Description

![Image](https://user-images.githubusercontent.com/115465230/211293338-8567931f-c2d6-4d74-b246-614baf3712e8.png)

​

## Acceptance Criteria

- [x] routes are clickable and direct to single route page
- [x] overflow-y is scrollable
- [ ] shows all routes with the same sector
      ​

## Tasks

- [ ] create Link for route names
- [ ] add styled components
- [ ] responsive design
- [ ] insert search bar
- [ ] create PR
