### ISSUE TITLE
Sprint_3/US_7#commentFunction_detailPage

### ISSUE THREAD

**Issue by jonatsuji** [jonatsuji/capstone-project#8]
## Value Proposition

**As a** user
**I want to** write and read comments on single routes
**so that** I can see and share opinions on these

## Description

![Sprint 3_ userStory7](https://user-images.githubusercontent.com/115465230/212335882-1359cda3-3c5a-41be-88de-b66c347f4b2e.png)

## Acceptance Criteria

- [ ] Write text for a comment and be able to post it
- [ ] Read comments from other user
- [ ] Choose between 1 and 5 stars for a rating
- [ ] See the rating from other users
- [ ] Put in a nickname to recognize the author

## Tasks

- [ ] Create comment component with a form (nickname and text input) and a container for written comments
- [ ] add local storage to save all written comments
- [ ] add optional rating function with stars
- [ ] add styling
- [ ] create PR

**Comment by Elgin-Schultz** [comment]
Makes sense to me. Looking forward to sseing it implemented!
